### PR TITLE
Bump min WP version to 5.9

### PR DESCRIPTION
**Pull request by Chouby**
All is in the title.

### CODE REVIEW

**Review by Screenfeed — CHANGES_REQUESTED** [review]
There are still some code related to backward compatibility (php, js, css).
For example:
- WP 5.6: https://github.com/polylang/polylang/blob/3fbfa8000512f449a23e3b68b2b9f754d583065a/include/olt-manager.php#L104-L111.
- WP 5.7: https://github.com/polylang/polylang/blob/3fbfa8000512f449a23e3b68b2b9f754d583065a/tests/phpunit/tests/test-email-strings.php#L27-L29 and https://github.com/polylang/polylang/blob/3fbfa8000512f449a23e3b68b2b9f754d583065a/tests/phpunit/tests/test-email-strings.php#L64-L66.
- WP 5.9: https://github.com/polylang/polylang/blob/3fbfa8000512f449a23e3b68b2b9f754d583065a/tests/phpunit/tests/test-widget-nav-menu.php#L72-L74 and https://github.com/polylang/polylang/blob/3fbfa8000512f449a23e3b68b2b9f754d583065a/tests/phpunit/tests/plugins/test-jetpack.php#L3.

**Comment by Chouby** [comment]
Good catch. I was not satisfied by the method used to skip the Jetpack test, so I changed it to use `markTestSkipped()`. While at it, I did the same for other plugins.

**Comment by Screenfeed** [comment]
@Chouby And now we can see that the tests are skipped because the plugins are not installed:
```
Run bash ./tests/bin/install-plugins.sh
checkdir:  cannot create extraction directory: /home/runner/work/polylang/polylang/tmp/wordpress/wp-content/themes
           No such file or directory
checkdir:  cannot create extraction directory: /home/runner/work/polylang/polylang/tmp/wordpress/wp-content/themes
           No such file or directory
```

```
There were 7 skipped tests:

1) Duplicate_Post_Test
This test requires the plugin Duplicate Post

2) Jetpack_Test
This test requires the plugin Jetpack

3) WP_Importer_Test::test_simple_import
This test requires the plugin WordPress Importer

4) Twenty_Fourteen_Test
This test requires the theme Twenty Seventeen

5) Twenty_Fourteen_Test
This test requires the theme Twenty Seventeen

6) Twenty_Fourteen_Test
This test requires the theme Twenty Seventeen

7) Twenty_Seventeen_Test
This test requires the theme Twenty Seventeen
```

**Comment by Chouby** [comment]
I opened a separated issue for this.

**Pull request merged**
