### PR TITLE
Current version of issue template

### PR DESCRIPTION
**Pull request by szepeviktor**
See https://help.github.com/articles/about-issue-and-pull-request-templates

### CODE REVIEW

**Comment by szepeviktor** [comment]
@Chouby

**Comment by Chouby** [comment]
Coul you clarify what issue you are trying to solve? It looks to me that the issue template is working as expected.

**Comment by szepeviktor** [comment]
Right now you r are using the **old** file path/name of the GitHub issue template.
This PR moves/renames it to the updated one: https://help.github.com/articles/about-issue-and-pull-request-templates

**Comment by Chouby** [comment]
As I understood this doc `ISSUE_TEMPLATE` is a directory where we could store several issue templates. It's not the issue template itself (unique in our case) which must be named that way.

**Comment by szepeviktor** [comment]
> `ISSUE_TEMPLATE` is a directory

No, it is a File.

**Comment by szepeviktor** [comment]
See https://github.com/Yoast/wordpress-seo/blob/trunk/.github/ISSUE_TEMPLATE.md

**Comment by szepeviktor** [comment]
Hello @Chouby!
There are 5 year old issues and 300+ PHPStan ignored errors.
May I help cleaning up this project?

**Pull request closed without merging**
