### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
Found some misspellings.

This PR removes the French smell. Only the public method `get_flag_informations` remains.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Add `typos` to CI!

`.typos.toml`
```toml
[files]
extend-exclude = [
    ".git/",
    "flags/??.png",
    "settings/flags.php",
    "settings/languages.php",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "Jani Alha",
    "Thanks to captin411",
    "'bs_BA'",
    "<!\\[CDATA\\[non-classe\\]\\]>",
]

[default.extend-words]

[default.extend-identifiers]
"OLT_Manager_Test" = "OLT_Manager_Test"
"PLL_OLT" = "PLL_OLT"
"PLL_OLT_Manager" = "PLL_OLT_Manager"
"get_post_stati" = "get_post_stati"
"test-olt-manager" = "test-olt-manager"
# TODO information
"get_flag_informations" = "get_flag_informations"
```

**Comment by szepeviktor** [comment]
@Chouby Here you go.

**Review by Hug0-Drelon — APPROVED** [review]

**Comment by Chouby** [comment]
Thanks @szepeviktor. As usual, you are helping us to discover useful tools. 12 years of typos gone in one PR!
@Hug0-Drelon Could you restore the filename `test-olt-manager.php`?

**Comment by Chouby** [comment]
Thank you very much @szepeviktor !

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
