### PR TITLE
Improve .typos.toml

### PR DESCRIPTION
**Pull request by szepeviktor**
- use TAB-s to [indent lines](https://github.com/polylang/polylang/blob/62e0163522925b89572c9e8f32380b2268160b1c/.editorconfig#L11)
- allow French word only in context

### CODE REVIEW

**Comment by szepeviktor** [comment]
@Chouby Friendly ping 🏓

**Comment by Screenfeed** [comment]
@szepeviktor What is the advantage of moving some words from `default.extend-words` to `default.extend-ignore-re`?

**Comment by szepeviktor** [comment]
In `words` "exemple" will match any occurrence of exemple.
As a regexp "Etiquette exemple" will match only that French phrase.

**Comment by Screenfeed** [comment]
I see. So if we use "exemple" in another French phrase, we will have to add this phrase as a regex, but this prevents typos where we could write "exemple" instead of "example". And since `words` cannot contain space characters, we cannot keep "Etiquette exemple" in it.
Thank you for the explanation.

**Comment by Screenfeed** [comment]
If you don't mind, I'll push a commit to group and sort things.

**Review by Screenfeed — APPROVED** [review]

**Comment by szepeviktor** [comment]
OK.

**Comment by Screenfeed** [comment]
And sorry for the delay Viktor.

**Comment by Chouby** [comment]
Thank you @szepeviktor :)

**Pull request merged**
