### PR TITLE
Change Admin menu Background Color

### PR DESCRIPTION
**Pull request by sebastienserre**
Add a background color on "Show All Languages" admin menu if it's filtered on a language.
It will maybe avoid some support request from customers who do not find their content.

Edit >For the latest modifications See [the comment](https://github.com/polylang/polylang/pull/821#issuecomment-854504920) below

### CODE REVIEW

**Comment by sebastienserre** [comment]
All Languages shown:
show-all-languages
Language filtered:
languages-filtered

**Comment by sebastienserre** [comment]
Effectively, the color is not OK with the "Sunrise" Admin Colour Scheme.
sunrise
it's OK with the Warning Orange color:
screenshot-2021-04-15-16-52

**Comment by manooweb** [comment]
I think the red color code you use first wasn't the Polylang red backgroud color `a03f3f` because it works pretty well with it

image

In your last proposition with the sunrise theme, why didn't you use the WordPress orange sunrise background color `dd823b` ?

image

It seems to me we should keep the white text color whatever the background we will choose espcially if we use the light theme

image

image

**Comment by manooweb** [comment]
The Polylang red `a03f3f` seems to be the right choice.
image

See https://wpsyntex.slack.com/archives/C017GJQBZP1/p1620050707007400

For the light I decided to also override the text color with white instead of grey
image

image

For all the other themes it's already in white

**Review by raaaahman — APPROVED** [review]
Tested with [Wave tool](https://wave.webaim.org/), no low contrast reported.

**Pull request merged**
