### PR TITLE
Fix dropdown rendering

### PR DESCRIPTION
**Pull request by olegstepura**
* Remove url property of `$item`:
   if empty string here - the link leads to 'undefined'
* Add `attr_title` to all items: 
   else `title` property is used and you see some HTML code with `<img src=...` on hover instead of pure text title.

### CODE REVIEW

**Comment by Chouby** [comment]
Thanks for the PR.

1. It seems that HTML5 allows not to add an `href` attribute for the `a` tag. Does it cause an issue for you? Otherwise not setting `$item->url` creates a link to `mysite/#pll_switcher` which is not very elegant. I would prefer  `$item->url = '#'` which would link to `mysite/#`. What do you think?

2. I am reluctant to add any title attribute because the included information is at best useless, at worst painful for users using a screen reader (See the ticket https://core.trac.wordpress.org/ticket/24766 which decided the removal of title attributes in WP Core). Moreover other menu items would get an attribute title only if it has been filled for each item in Appearence > Menus (empty by default). So there is a high risk not to be consistent with other menus items on most websites.

I guess the title attribute is added by your theme as a copy of the item html (which causes the  `<img src=...`). As explained, I believe that's wrong. I hope some day theme authors will stop doing that. I suggest that you use a filter to just remove this title attribute if it is a copy of the html (hopefully you'll find one after the theme has added it).

**Comment by olegstepura** [comment]
1. Actually `mysite/#pll_switcher` is ok since it can even scroll to an element if it is not visible. I think leaving it so it better.
2. maybe it would be good to set `attr_title` to an empty string. This sounds like best solution to both worlds.

Please let me know if I need to modify my PR

**Comment by Chouby** [comment]
I am not sure that an empty string for `attr_title` will fix all themes copying the item html. But if it does for some of them, then the change will be positive. Let's do like that.

**Comment by olegstepura** [comment]
I updated the PR making `attr_title` an empty string

**Comment by Chouby** [comment]
I did not merged your PR directly because of the remain non empty `attr_title` at line 93

**Comment by olegstepura** [comment]
Oh, sorry. How do we proceed?

**Comment by Chouby** [comment]
No worry. I fixed it myself in https://github.com/polylang/polylang/commit/5876975282c0b16d5a8c3e307209baa717908b36
I just wanted to explain why I did not merge the PR as is.

**Pull request closed without merging**
