### PR TITLE
Added a span wrapper for the current language name

### PR DESCRIPTION
**Pull request by AmitT**
span wrapper added to current language name so its syntax will fit to other language items and will be easier to style.

### CODE REVIEW

**Comment by Chouby** [comment]
I woul rather do the same as what's already done for other items.
See https://github.com/polylang/polylang/blob/2.2.5/frontend/frontend-nav-menu.php#L92
It seems that I forgot this one.

**Comment by AmitT** [comment]
Fixed. 
But, I think we should come with a better solution because margin-left:0.3em will work only for LTR languages.

**Comment by Chouby** [comment]
You are right for RTL languages. What's currently done doesn't work.
The original code was:
```php
$lang['flag'] . '&nbsp;' . esc_html( $lang['name'] )
```
In v1.9, I modified it to the current version:
```php
$lang['flag'] . '<span style="margin-left:0.3em;">' . esc_html( $lang['name'] ) . '</span>'
```
because someone requested the span wrapper as you did. I thought that removing the non breaking space was good but I needed to add the inline style not to break the style of existing sites. And I did not notice that I broke RTL languages :/

One solution could be to keep using the inline style but make it dependant on the text direction.

Another solution could be to add the non breaking space back. But  I would rather keep it outside the span wrapper like this:
```php
$lang['flag'] . '&nbsp;<span>' . esc_html( $lang['name'] ) . '</span>'
```
None of these solutions are perfect. What do you think?

**Comment by AmitT** [comment]
I think the first solution will be easier to override and  that's why it is better.
Actually, (if we leaving the backward compatibility issue) I prefer to add a class to every span and let the developers customize the CSS as they wish.

**Pull request merged**
