### PR TITLE
When updating options in REST, return all values

### PR DESCRIPTION
**Pull request by Screenfeed**
Closes https://github.com/polylang/polylang-pro/issues/2373.

When updating options in REST, return all values instead of only the updated ones.

### CODE REVIEW

**Review by Hug0-Drelon — CHANGES_REQUESTED** [review]
LGTM, but we may want to cover with a test.
What do you think @Screenfeed?

**Comment by Screenfeed** [comment]
@Hug0-Drelon [There is](https://github.com/polylang/polylang/blob/5df10b0301ed92234a9af7596dd843df195d62a7/tests/phpunit/tests/test-rest-settings.php#L95), but it asserts the new values only.

**Comment by Hug0-Drelon** [comment]
> @Hug0-Drelon [There is](https://github.com/polylang/polylang/blob/5df10b0301ed92234a9af7596dd843df195d62a7/tests/phpunit/tests/test-rest-settings.php#L95), but it asserts the new values only.

So the behavior isn't covered, right?

**Comment by Screenfeed** [comment]
It doesn't test that all values are returned indeed, do you think it's worth testing?

**Comment by Hug0-Drelon** [comment]
> It doesn't test that all values are returned indeed, do you think it's worth testing?

I think it worth doing that but in a tiny test, just asserting two arrays with only one value updated.

**Comment by Screenfeed** [comment]
Done in [9fe1d3c](https://github.com/polylang/polylang/pull/1588/commits/9fe1d3c728b0e32a469ba83f280243c624a713ec).

**Review by Hug0-Drelon — APPROVED** [review]

**Pull request merged**
